<style>

    @font-face {
        font-family: arial;
        font-weight: normal;
        font-style: normal;
    }

    html, body {
        margin:0;
        padding:0;
    }

    body {
        text-align:left;
        font:100% arial;
        background:#fff;
    }

    h1, h2, h3, h4, h5, h6, p, div, ul , li {
        margin:0;
        padding:0;
        color:rgb(0,0,0);
    }

    p {
        color:#333;
    }

    a {
        color:#995522;
        text-decoration:none;
    }

    #mainContent {
        position:relative;
        padding:0;
        width:930px;
        margin:25px auto;
        border:1px solid #00CCFF;
        border-radius: 10px;
    }

    #mainContent #header {
        height:110px;
        background-color:#00CCFF;
        border-radius:10px 10px 0 0;
    }

    #mainContent #header h1 {
        font-size:2.5em;
        padding:10px;
    }

    #mainContent #header ul {
        list-style:none;
        padding-left:5px;
    }

    #mainContent #header ul li {
        float:left;
        padding-left:5px;
    }

    #mainContent #header ul li a {
        color:#000;
        font-size:1.2em;
        text-decoration:underline;
    }

    #mainContent #header ul li a:hover {
        color:#fff;
    }

    #mainContent #mainArticle h2 {
        font-size:2em;
        padding: 10px 10px 10px;
    }

    #mainContent #mainArticle table {
        font-size: 1.2em;
        border:1px solid #00CCFF;
        margin:auto 10px 40px;
        width:910px;
        border-collapse:collapse;
    }

    #mainContent #mainArticle table th {
        border:colapse;
        background-color:#00CCFF;
        text-align:left;
    }

    #mainContent #mainArticle table th,td  {
        border:1px solid #00CCFF;
        margin:0;
        padding: 5px;
    }

    #mainContent #footer p {
        padding:10px;
    }

    #mainArticle #myTable a {
        font-size:1.2em;
        cursor:pointer;
    }

</style>
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <title>Shopping basket</title>

    <link href="main.css" rel="stylesheet" type="text/css" />

</head>
<body>
<div id="mainContent">
    <div id="header">
        <h1>МОЯ КОРЗИНА</h1>

        <ul>
            <li><a href="">Link 1</a> <b>&#124;</b></li>
            <li><a href="">Link 2</a> <b>&#124;</b> </li>
            <li><a href="">Link 3</a> <b>&#124;</b> </li>
            <li><a href="">Link 4</a> <b>&#124;</b> </li>
            <li><a href="">Link 5</a></li>
        </ul>
    </div>
    <div id="mainArticle">
        <h2>Shopping Basket</h2>

        <table id="myTable">
            <tr>

                <th>User ID</th>
                <th>Product ID</th>
                <th>Quantity</th>
                <th>Total Amount</th>
            </tr>
            <?php foreach ($basket as $elem): ?>
            <tr>
                <td><?php echo $elem['user_id']; ?></td>
                <td><?php echo $elem['product_id']; ?></td>
                <td><?php echo $elem['amount']; ?></td>
                <td><?php echo $elem['amount'] * 100; ?></td>
                <?php endforeach; ?>
            </tr>
        </table>
    </div>
    <div id="footer">
        <p>&copy; Copyright BT Expedite 2014</p>
    </div>
        <div class="buttons">
            <a href="main" class="register-link">Перейти на главную страницу</a>
        </div>
</div>
<script src="js.js"></script>
</body>
</html>

