<div class="container">
    <h3>Catalog</h3>
    <div class="card-deck">
        <?php foreach ($products as $product): ?>
        <div class="card text-center">
            <a href="#">
                <div class="card-header">
                    Hit!
                </div>
                <img class="card-img-top" widht=400 height=300 src=<?php echo $product['image']?> alt="Card image">
                <div class="card-body">
                    <?php echo $product['productName'];?>
                    <a href="#"><h5 class="card-title"><?php echo $product['description'];?></h5></a>
                    <div class="card-footer">
                        <?php echo ($product['price'] . ' руб'); ?>
                    </div>
                    <form action="/addProduct" method="POST">
                        <input type="hidden" name="product_id" value="<?php echo $product['id']; ?>">
                        <input type="submit" value="Добавить в корзину">
                    </form>
                </div>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
        <div class="buttons">
            <a href="basket" class="register-link">Перейти в корзину</a>
        </div>
    </div>
</div>

<style>
    body {
        font-style: italic;
    }

    a {
        text-decoration: none;
    }

    a:hover {
        text-decoration: none;
    }

    h3 {
        line-height: 3em;
    }

    .card {
        float: left;
        margin-right: 20px;
        margin-left: 35px;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 16px;
        color: gray;
        background-color: white;
    }

    .text-muted {
        font-size: 11px;
    }

    .card-footer{
        font-weight: bold;
        font-size: 18px;
        background-color: white;
    }
</style>


