<!DOCTYPE html>
<html>
<head>
    <title>Job Application Registration Form</title>
    <style>
        body {
            font-family: Calibri, sans-serif;
            background-color: #72b7f4;
        }
        h2 {
            color: #232729;
            text-align: center; /* Center align the title */
        }
        form {
            background-color: #bfddf7;
            max-width: 500px;
            margin: 0 auto;
            padding: 30px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        label {
            display: block;
            margin-bottom: 10px;
            color: #333333;
        }
        input[type="text"],
        input[type="email"],
        input[type="password"],
        input[type="file"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #cccccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-bottom: 15px;
            background-color: #ffffff; /* Set background color to white */
        }
        select {
            width: 100%;
            padding: 10px;
            border: 1px solid #cccccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-bottom: 15px;
        }
        input[type="submit"] {
            background-color: #1a73e8;
            color: #ffffff;
            border: none;
            padding: 12px 24px;
            border-radius: 4px;
            cursor: pointer;
        }
        input[type="submit"]:hover {
            background-color: #0059b3;
        }
    </style>
</head>
<body>
<h2>Job Application Registration</h2>
<form action="" method="POST">
    <label for="name">Full Name:</label>
    <label style="color:red"><?php
        if (isset ($errors['name'])) {
            echo $errors['name'];
        }
        ?></label>
    <input type="text" id="name" name="name" required>
    <label for="email">Email Address:</label>
    <label style="color:red"><?php
        if (isset ($errors['email'])) {
            echo $errors['email'];
        }
        ?></label>
    <input type="email" id="email" name="email" required>
    <label for="password">Password:</label>
    <label style="color:red"><?php
        if (isset ($errors['password'])) {
            echo $errors['password'];
        }
        ?></label>
    <input type="password" id="password" name="password" required>
    <label for="userPassword">Repeat Password:</label>
    <label style="color:red"><?php
        if (isset ($errors['repeat_pwd'])) {
            echo $errors['repeat_pwd'];
        }
        ?></label>
    <input type="password" id="userPassword" name="repeat_pwd" required>
        <br><br>
    <input type="submit" value="Submit Application">
</form>
</body>
</html>